spring.application.name=sample-mcp
server.port=${PORT:8090}
spring.threads.virtual.enabled=true
spring.ai.mcp.server.protocol=stateless
spring.ai.mcp.server.streamable-http.mcp-endpoint=/
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER_URI}

# For use with a reverse proxy
#server.forward-headers-strategy=framework
